In [1]:
import nouma

In [2]:
import numpy as np

In [3]:
scale = 2 ** 40
parms = nouma.EncryptionParameters.new(8192, [60, 40, 40, 40])

In [4]:
context = nouma.Context(parms)
keygen = nouma.KeyGenerator(context)
secret_key = keygen.secret_key()
public_key = keygen.public_key()
relin_keys = keygen.relin_keys()
gal_keys = keygen.galois_keys()

In [5]:
encoder = nouma.CKKSEncoder(context)
encryptor = nouma.SymmetricEncryptor(context, secret_key)
decryptor = nouma.Decryptor(context, secret_key)
evaluator = nouma.Evaluator(context)

In [6]:
A = np.array([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4]
], dtype=np.float64)

In [7]:
B = np.array([
    [5, 6, 7, 8],
    [5, 6, 7, 8],
    [5, 6, 7, 8],
    [5, 6, 7, 8]
], dtype=np.float64)

In [8]:
A @ B

array([[50., 60., 70., 80.],
       [50., 60., 70., 80.],
       [50., 60., 70., 80.],
       [50., 60., 70., 80.]])

In [9]:
A[:, 0]

array([1., 1., 1., 1.])

In [10]:
A[:, 1]

array([2., 2., 2., 2.])

In [11]:
A[:, 2]

array([3., 3., 3., 3.])

In [12]:
A[:, 3]

array([4., 4., 4., 4.])

In [13]:
B[:, 0]

array([5., 5., 5., 5.])

In [14]:
B[:, 1]

array([6., 6., 6., 6.])

In [15]:
B[:, 2]

array([7., 7., 7., 7.])

In [16]:
B[:, 3]

array([8., 8., 8., 8.])

In [17]:
Acol1 = A[:, 0]
Acol2 = A[:, 1]
Acol3 = A[:, 2]
Acol4 = A[:, 3]

In [18]:
Bcol1 = B[:, 0]
Bcol2 = B[:, 1]
Bcol3 = B[:, 2]
Bcol4 = B[:, 3]

In [19]:
Acol1 * Bcol1 + Acol2 * Bcol1 + Acol3 * Bcol1 + Acol4 * Bcol1

array([50., 50., 50., 50.])

In [20]:
Acol1 * Bcol2 + Acol2 * Bcol2 + Acol3 * Bcol2 + Acol4 * Bcol2

array([60., 60., 60., 60.])

In [21]:
Acol1 * Bcol3 + Acol2 * Bcol3 + Acol3 * Bcol3 + Acol4 * Bcol3

array([70., 70., 70., 70.])

In [22]:
Acol1 * Bcol4 + Acol2 * Bcol4 + Acol3 * Bcol4 + Acol4 * Bcol4

array([80., 80., 80., 80.])

In [23]:
Acol1 = encryptor.encrypt(encoder.encode(Acol1, scale))
Acol2 = encryptor.encrypt(encoder.encode(Acol2, scale))
Acol3 = encryptor.encrypt(encoder.encode(Acol3, scale))
Acol4 = encryptor.encrypt(encoder.encode(Acol4, scale))

In [24]:
Bcol1 = encryptor.encrypt(encoder.encode(Bcol1, scale))
Bcol2 = encryptor.encrypt(encoder.encode(Bcol2, scale))
Bcol3 = encryptor.encrypt(encoder.encode(Bcol3, scale))
Bcol4 = encryptor.encrypt(encoder.encode(Bcol4, scale))

In [25]:
Ccol1 = evaluator.multiply(Acol1, Bcol1)
evaluator.add_inplace(Ccol1, evaluator.multiply(Acol2, Bcol1))
evaluator.add_inplace(Ccol1, evaluator.multiply(Acol3, Bcol1))
evaluator.add_inplace(Ccol1, evaluator.multiply(Acol4, Bcol1))

In [26]:
Ccol2 = evaluator.multiply(Acol1, Bcol2)
evaluator.add_inplace(Ccol2, evaluator.multiply(Acol2, Bcol2))
evaluator.add_inplace(Ccol2, evaluator.multiply(Acol3, Bcol2))
evaluator.add_inplace(Ccol2, evaluator.multiply(Acol4, Bcol2))

In [27]:
Ccol3 = evaluator.multiply(Acol1, Bcol3)
evaluator.add_inplace(Ccol3, evaluator.multiply(Acol2, Bcol3))
evaluator.add_inplace(Ccol3, evaluator.multiply(Acol3, Bcol3))
evaluator.add_inplace(Ccol3, evaluator.multiply(Acol4, Bcol3))

In [28]:
Ccol4 = evaluator.multiply(Acol1, Bcol4)
evaluator.add_inplace(Ccol4, evaluator.multiply(Acol2, Bcol4))
evaluator.add_inplace(Ccol4, evaluator.multiply(Acol3, Bcol4))
evaluator.add_inplace(Ccol4, evaluator.multiply(Acol4, Bcol4))

In [29]:
encoder.decode(decryptor.decrypt(Ccol1))

array([50., 60., 70., 80.])

In [30]:
encoder.decode(decryptor.decrypt(Ccol2))

array([60., 70., 80., 50.])

In [31]:
encoder.decode(decryptor.decrypt(Ccol3))

array([70., 80., 50., 60.])

In [32]:
encoder.decode(decryptor.decrypt(Ccol4))

array([80., 50., 60., 70.])